services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm-gateway
    restart: unless-stopped
    ports:
      - "127.0.0.1:81:81"
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      gateway_internal:
        ipv4_address: 172.18.1.5
      global_network:

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run --token ${CF_TUNNEL_TOKEN}
    depends_on:
      - npm
    networks:
      gateway_internal:
        ipv4_address: 172.18.1.10

volumes:
  npm_data:
  npm_letsencrypt:

networks:
  gateway_internal:
    name: gateway_internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
          ip_range: 172.18.1.64/26
          gateway: 172.18.1.254
          
  global_network:
    name: ${GLOBAL_NETWORK_NAME}
    external: true