user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

# Capa de Bases de Datos (L4)
stream {
    allow 127.0.0.1;                        # Tunel SSH
    allow 172.16.0.0/24;                    # Segmento DMZ (Nginx-to-Nginx)
    deny all;

    include /etc/nginx/conf.d/streams.conf;
}

# Capa Web de Control (L7)
http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        
        allow 127.0.0.1;                        # Tunel SSH
        allow 172.16.0.0/24;                    # Segmento DMZ (Nginx-to-Nginx)
        deny all;

        location / {
            add_header Content-Type text/plain;
            return 200;
        }
    }
}