user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

# --- PROXY DE BASES DE DATOS (Layer 4 - TCP) ---
stream {
    # DNS interno de Docker para resolver nombres si fuera necesario
    resolver 127.0.0.11 valid=5s;

    # Túnel para MariaDB
    server {
        listen 3306;
        # Usamos la IP fija definida en el compose para máxima velocidad y fiabilidad
        proxy_pass 172.18.2.20:3306;
        proxy_connect_timeout 5s;
        proxy_timeout 30s;
    }

    # Túnel para MongoDB
    server {
        listen 27017;
        proxy_pass 172.18.2.30:27017;
        proxy_connect_timeout 5s;
        proxy_timeout 30s;
    }

    # Túnel para Redis
    server {
        listen 6379;
        proxy_pass 172.18.2.40:6379;
        proxy_connect_timeout 5s;
        proxy_timeout 30s;
    }
}

http {
    access_log off;
    server {
        listen 80;
        location / {
            return 200 'Database Gateway Operational - Segment 172.18.2.x\n';
            add_header Content-Type text/plain;
        }
    }
}