upstream mariadb_backend {
    server mariadb-database:3306;
}

upstream mongodb_backend {
    server mongodb-database:27017;
}

upstream redis_backend {
    server redis-database:6379;
}

server {
    listen 3306;
    proxy_pass mariadb_backend;
    
    # --- LISTA BLANCA ---
    allow 127.0.0.1;          # Tunel SSH
    allow 172.16.0.0/24;      # Segmento DMZ (Nginx-to-Nginx)
    deny all;
}

server {
    listen 27017;
    proxy_pass mongodb_backend;
    
    # --- LISTA BLANCA ---
    allow 127.0.0.1;          # Tunel SSH
    allow 172.16.0.0/24;      # Segmento DMZ (Nginx-to-Nginx)
    deny all;
}

server {
    listen 6379;
    proxy_pass redis_backend;

    # --- LISTA BLANCA ---
    allow 127.0.0.1;          # Tunel SSH
    allow 172.16.0.0/24;      # Segmento DMZ (Nginx-to-Nginx)
    deny all;
}
