stream {
    # DNS interno de Docker
    resolver 127.0.0.11 valid=5s;

    # --- MARIADB ---
    server {
        listen 3306;
        # Usamos la variable con la IP fija para saltarnos el DNS y asegurar persistencia
        set $mariadb_target "172.18.2.20"; 
        proxy_pass $mariadb_target:3306;
        
        # Filtro de seguridad (Firewall)
        allow 127.0.0.1;        # Localhost
        allow 172.16.0.0/12;    # Todo el rango privado de Docker (incluye 172.18.x.x)
        deny all;               # Bloqueo total a cualquier otra cosa
    }

    # --- MONGODB ---
    server {
        listen 27017;
        set $mongo_target "172.18.2.30";
        proxy_pass $mongo_target:27017;
        
        allow 127.0.0.1;
        allow 172.16.0.0/12;
        deny all;
    }

    # --- REDIS ---
    server {
        listen 6379;
        set $redis_target "172.18.2.40";
        proxy_pass $redis_target:6379;

        allow 127.0.0.1;
        allow 172.16.0.0/12;
        deny all;
    }
}